# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6746f20b1f669e3096a5f428fc9d46b2ca5b166ce11e93de570eb5845c27fa9e145e82024c4761606c4f302fc4b890337d98d8d6d63ad5ddfc2730570225ac9

test:
  secret_key_base: 9ab6fe1239f8db4eb8792f10a6d2deb0983728832d8d390c4b87991eba7ba5b85af45bee444badb58e80514aa23e269c610cb8dfe6393969b4f4467ed5ffcd01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
